### ISSUE TITLE
Owner Role

### ISSUE THREAD

**Issue by lizumberfield** [d-acts/d-acts#29]
During recent calls (4/27, Mathias B., Chris S., John J., Sarah B., Liz U.; 4/30; OBIB call) we discussed the need for a new class to represent an ownership role in D-Acts. This was particularly motivated by analysis of clinical consent forms and the bellow sentence: 

 _I DONATE and authorize [HOSPITAL_X] to own, use, retain, preserve, manipulate, analyze, or dispose of any excess tissues, specimens, or parts of organs that are removed from my body during the procedures described above and are not necessary for my diagnosis or treatment._

**Comment by mbrochhausen** [comment]
Neil Otte and I had a very fruitful discussion about that and I will give my position after that discussion (which of course Neil contributed to) here: 
1. We need to move obligor and obligee role under deontic role (https://github.com/d-acts/d-acts/issues/30). In that process we need to revise the textual definitions of those roles. I might end up obsoleting the IRIs of those two roles and create them de novo.
2. Neil and I think (I believe) that deontic roles are atomic in the sense that a deontic role that is an obligor role cannot have obligee roles as parts. In this sense these roles represent more closely individual rights and obligations. Based on that thinking I think ownership should not be represented as a deontic role (but it has, of course, deontic roles as part).
3. Based on this consideration I propose to represent ownership as a subclass of "role in human social process (http://purl.obolibrary.org/obo/OMRSE_00000024). 
4. My proposed definition for ownership is "A role in a human social process that is mutually dependent on a property role and that is the outcome of a deontic declaration and that provides control over the property by deontic roles, that are its parts and exclusive."

**Comment by neilotte** [comment]
Regarding 'role in human social process', the definition is 'A role inhering in an entity realized by social interactions in human society.' I'm not familiar with this class. Is this definition to be read as: 1. Any instance is only ever realized in social interactions in human society? Or is the definition better read as: 2. Among the conditions for the role's realization are social interactions in human society? Presently, it reads like: 3. Every instance of 'role in human social process' must be realized by some social interactions in human society.  

Only 2 seems correct. 1 and 3 seem too restrictive. 

Some comments on the proposed definition of ownership: 

1. The clause '...that provides control...' implies the role provides control. I believe what is intended is that the the role is realized in the role-bearer controlling the property. Also, it isn't clear what 'that are its parts and exclusive' means. 
Here's a rephrase: 
"A role in a human social process that is
 a. mutually dependent on a property role and 
 b. that is the outcome of a deontic declaration and 
 c. whose bearer exercises exclusive control over the property, where this control is permitted by one or more deontic roles, which are parts of the ownership role.

2. If every ownership role is the outcome of some deontic declaration, this seems to exclude cases where a standing declaration creates an ownership role (e.g. ownership transferral due to the death of a previous owner). 

3. One issue that came up repeatedly in my work on the product life cycle ontology was the issue of treating property and economic goods as role bearers. This worked so long as property was an Independent Continuant, but because roles can't inhere in Dependent Continuants, I couldn't assert that Intellectual Property (in particular, software) could bear roles. There is a similar concern with 'property role'. What we ended up doing was asserting that ICE's participate in stases during which they _count _as_ 'digital goods' and hence as property. https://philarchive.org/archive/OTTAOA-3 
        There are similar concerns for renting and owning usage rights. Let's say I have a Netflix subscription. One might want to regard this as a special case of ownership, where I pay for and now own a right to stream and access content. The right is thereby my property. Now, if the right is an obligee role, then asserting that the right to stream and access content is my property and treating property as a role entails that obligee role must bear a property role (which it cannot of course). 
        These considerations provide some reason for dropping the requirement that every ownership role is mutually depends on some property role from the definition.

**Comment by mbrochhausen** [comment]
Neil: Many thanks! This is create.
1. +1 for you definition (modulo the changes motivated by 2&3)
2. You are right. I think it is fine to say that all ownership is based on social acts.I am not sure that that wording is appropriate, since it doesn't translate to a relationship. We cannot say that all ownership is the specified output of a social act, since in the cases of standing declarations the declaration does not have the role as its (immediate) output.
3. Yes, I agree, we should get rid of the part of the definition that requires a property role for every owner role. I wasn't sure about it. Your examples show it clearly doesn't work.

**Comment by lizumberfield** [comment]
Mathias and Neil: you've both put a lot of thought into this. Thank you!
Based on what I understand, I agree with the recommendations made here by
Neil.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by mbrochhausen** [comment]
The issue fas fixed by the following commit:
https://github.com/d-acts/d-acts/commit/a265506d6cf54cc14e605db42885d7edd100f2c0
